### ISSUE TITLE
Version QWebEngine

### ISSUE THREAD

**Issue by kalwinskidawid** [Salamek/qiosk#10]
Hey,
How can I check current version of QWebEngine? 
Do you plan to upgrade version to at least 6.6.0? 
Current qiosk does not support eg. `toStorted()`

**Comment by Salamek** [comment]
Hi, 
version of `QWebEngine` can be seen when calling `qiosk -v`
`QWebEngine` used by `qiosk` comes from your OS installed version, so for example on Archlinux:

```
$ qiosk -v
qiosk: 1.10.1
chromium: 118.0.5993.220
QWebEngine: 6.7.2
```

On Debian based systems it will be `QWebEngine` ~`6.4.2` and so on... so if you want newer version of QWebEngine and underlying Chromium, you need to install newer version of QWebEngine from backports/unstable (and so on applicable to your distro) repository

**Comment by kalwinskidawid** [comment]
Ouh, that strange, I tried the command before create the issue. 
The command return only qiosk version: 
![image](https://github.com/user-attachments/assets/8b5d6ddb-68a2-4e7c-a82e-ea0706b4296d)

MiniOS is a slimmed-down debian bookworm.

**Comment by Salamek** [comment]
-v displays this only in latest qiosk release and only when using QT6.2> so do fast `apt update && apt upgrade` ;-)
I'm personally using Debian 12 netinstall.iso + preseed config file to install kiosks...

**Comment by kalwinskidawid** [comment]
Could I ask you to share the preseed configuration file? :)

**Comment by Salamek** [comment]
I made a public version of preseed config i use, (removed SSH key injection, accounts creation, VPN and stuff)
https://preseed-api.salamek.cz/t7ScycxDuE  (UNTESTED)

It installs chromium-kiosk, VNC and tux-control

default password for chromium-kiosk user that is in sudoers is `qiosk`, for tux-control running on port 8051 admin@example.com `qiosk` and for VNC (default VNC port) `qiosk`

Install process is three stage process first standard pressed config is loaded from URL and does basic install and setup, then "firts-boot" service is created and computer is restarted... on first boot bash script is loaded that does rest of the work

**Comment by kalwinskidawid** [comment]
Thank you so much! `qiosk` password does not work, but I'll try figureout why.

**Comment by Salamek** [comment]
Possibly command for setting a password for chromium-kiosk user that i added for this public pressed release did not work (i'm not using passwords but ssh key pairs)... how i said, it is not tested...

**Comment by Salamek** [comment]
Ok, i have tested the preseed file now, and fixed some stuff, now it should work as intended, also added it into docs as an install option https://github.com/Salamek/chromium-kiosk/blob/master/.docs/README.md#debian-automated-install

**Comment by kalwinskidawid** [comment]
Great, thank you! Nice improvement! I'm just wondering if it's a good strategy to add chromium-kiosk to sudo users, but on the other hand it's rather impossible to go from chrome view to console anyway(?).

**Comment by Salamek** [comment]
Well terminal switching should still work (Ctrl+Alt+F*) i did not block that since i don't use it anywhere with connected keyboard... also `chromium-kiosk` user is in `sudoers` so ppl can switch to root somehow without enabling root SSH and they still need to provide a password for `chromium-kiosk` to do that, also it is on person using this preseed to secure it as they seem fit...

**Comment by kalwinskidawid** [comment]
Sure, thanks! I have two more dump questions :) 
1. How to turn off chromium-kiosk for a while to get access to terminal on screen (Ctrl+Alt+F does not work)
2. How to run from ssh `qiosk -v` , it throws `qt.qpa.xcb: could not connect to display`

**Comment by Salamek** [comment]
1. Edit `var/lib
/chromium-kiosk/.xinitrc` , comment out `exec chromium-kiosk run --config_prod --log_dir=$HOME && killall -u $USER` by adding `#` in front of it and put `exec xterm` on another line after it, then run `killall -u chromium-kiosk`. That will restart X11 and start `xterm` instead of `chromium-kiosk`

2. Run `chromium-kiosk system_info` to obtain DISPLAY id (usually `:0`), then run `DISPLAY=:0 qiosk -v` (BTW: this will work only when X11 is running)

How i said before, upgrade of `QWebEngine` is not something on my side to do, `qiosk` uses system installed `QWebEngine` so if you need newer version (6.6.2) you can use Debian testing, see https://linuxiac.com/how-to-switch-from-debian-stable-to-testing/  (and if qiosk starts complaining not finding correct QWebEngine version, just link 6.4.0 to 6.6.2, it should work OR rebuild qiosk from source)

**Comment by kalwinskidawid** [comment]
Okay, it's much more clear to me :) I tried `chromium-kiosk system_info` / `qiosk -v` on different user, not on chromium-kiosk. I thought that I can run eg. on `root`. 

One more request / idea, what do you think about adding any information (maybe just an extra window) when the site is not available? 
I checked this case and it only shows a blank white page now.

**Comment by Salamek** [comment]
Ah, yes these commands needs to be run under `chromium-kiosk` user.

Qiosk already reports webpage errors correctly,  and reloads automatically when URL becomes available... if you see a blank page it is most likely issue on server side, not sending correct HTTP error code and no body (200 + empty body = blank white page).

![Screenshot_20241008_180903](https://github.com/user-attachments/assets/007285f5-d5aa-4131-895b-14dd241afdee)
![Screenshot_20241008_180844](https://github.com/user-attachments/assets/ec900b63-ab68-459b-b7f3-cb3de6b7e12d)
![Screenshot_20241008_180320](https://github.com/user-attachments/assets/649db22d-3590-45d6-b6b8-349c2eb2bb92)

**Comment by kalwinskidawid** [comment]
Okay, so I have to check nginx on my server 😮 
one more question about config whitelist, is it just standard regex? 
My homepage is `http://192.168.0.50:85`, I tried do a white list `http:\/\/192\.168\.0\.50:85.+` or `192.168.0.50:85.+` or `192.168.0.50.+` or with asterisk. However always I got blank page and `/var/lib/chromium-kiosk/chromium_kiosk_kiosk.log` is also empty

**Comment by Salamek** [comment]
White list uses glob format (URL is a path), not regex, so it should be `http://192.168.0.50:85*` and/or `http://192.168.0.50:85/**`

**Comment by Salamek** [comment]
@kalwinskidawid i assume this is resolved now?

**Comment by kalwinskidawid** [comment]
Almost, the whitelist works fine, but I wonder if it should work this way. I mean, for example, on the home page I have an href to google.com, the page tries to load, but it's off the whitelist - so it just displays a white page. Shouldn't it be that if it is off the list it should redirect back to the main page?

**Comment by Salamek** [comment]
Blacklisted URLs should do nothing when clicked.

**Comment by kalwinskidawid** [comment]
Blacklist? I suppose you only handle the whitelist. Blacklist = !whitelist, right? 
It's weird, I have a button on the home page that redirects (just the href) to youtube and when I clicked it tried to redirect me, I saw the loading bar (for a second). So it seems that the blocker exists, but works too late?

**Comment by Salamek** [comment]
Yes blacklisted URL is !whitelist, blocking is done before attempt to load any data, should not trigger any loading. Can you provide your config so i can test? (or minimal !working example). Since it works ok for me...

**Comment by kalwinskidawid** [comment]
Thank you, I made a simple page and it works as you said - the redirect does not work
```html
<html>
<head>
</head>
<body>
	<a href="https://apple.com" style="padding:25px; background-color:lime; color:black">Go to apple </a> 
</body>
</html>
```
Example of config (only most important things): 
```yaml
FULL_SCREEN: true 
HOME_PAGE: 'http://10.35.20.85:9090'
WHITE_LIST:
  ENABLED: true  # is white list enabled
  URLS: ['http://10.35.20.20:85*','http://10.35.20.85:9090/**'] 
NAV_BAR:
  ENABLED: false # is nav bar enabled
```

The problem is with the target, when you add `target=“_blank”` it will create a new tab, but whitelist will block it, so I get a blank page. The navbar is hidden so there is no way to go back to the previous page.

**Comment by kalwinskidawid** [comment]
Super! That works! Sneaky workaround hah, I assumed you would use the interceptor, but this sneaky workaround is good too 🥇

**Comment by Salamek** [comment]
Hmm i just tested QWebEngineSettings::ErrorPageEnabled = false and that just gave a white page instead of error page, so i think that my workaround is a better solution (sadly). So if this is all feel free to close this issue.

**Comment by kalwinskidawid** [comment]
In that case, your idea is a better solution than an error page :)
That's all from my side for now, THANK YOU very much for your help! 
In the end I used Arch linux and it seems to me that it has more customizability. Plus it has the latest QT :)
