### ISSUE TITLE
Is there a 32-bit version of qiosk available for Raspbian?

### ISSUE THREAD

**Issue by Ozzard** [Salamek/qiosk#2]
I've been unable to install qiosk in the most recent RPi 32-bit Lite, as there's no qt5webenginewidgets5 package.  Is qiosk 64-bit only?  If so, there's another breaking change on chromium-kiosk 2.0, which is that it's aarch64 only.  If not, can anyone tell me where I'd find that package?

**Comment by Salamek** [comment]
Don't use Rasbian, Rasbian is just more ~broken version of Debian with some Raspberry specific stuff preinstalled && configured, has some missing packages in repo (like qt5webenginewidgets5, idk why)...

What i personally use is Debian aarch64, but armhf shoudl work too... see https://github.com/Salamek/chromium-kiosk/tree/master/.docs#raspberry-pi 

(also chromium was broken in Rasbian see https://github.com/Salamek/chromium-kiosk/issues/51)


Qiosk is build from armhf (32bit) and aarch64 (64bit)

**Comment by Ozzard** [comment]
Thanks - hadn't seen the constraints in the Raspberry Pi docs, which is entirely my fault.
