### ISSUE TITLE
aarch64 version for Arch Linux Arm?

### ISSUE THREAD

**Issue by pszafer** [Salamek/qiosk#3]
Hi,
Can you make aarch64 version for Arch Linux Arm?
I see that your repo only contains x86_64 build for Arch Linux

**Comment by Salamek** [comment]
... as soon as i find out how to cross compile for aarch64 on x86_64 Archlinux :sob: 
looks like i will need to set up Archlinux ARM qemu VM to do these builds... :roll_eyes:

**Comment by Salamek** [comment]
@pszafer HI, aarch64 should be available now! Added in https://github.com/Salamek/qiosk/commit/edbf6ac269ca0eea86acaecea565bc83f30095e9
