### ISSUE TITLE
"&&=" unexpected token =

### ISSUE THREAD

**Issue by mishoboss** [Salamek/qiosk#4]
I'm getting this JS error when I open a given page in qiosk. This essentially means the JS interpreter doesn't like this relatively new syntax. Can it be updated to the latest available version?

**Comment by Salamek** [comment]
There is qt6-qiosk package available that replaces normal qiosk and it is build on qt6 that should have newer webengine...

To install it under debian 12 just run `apt install qt6-qiosk`

To install it under debian 11 follow info after step 6. https://github.com/Salamek/chromium-kiosk/tree/master/.docs#debian

**Comment by mishoboss** [comment]
I get this when I try to install on debian 11. Backports repo was added.

`Package qt6-qiosk is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source`

**Comment by Salamek** [comment]
Did you do `apt update` before trying to install?

**Comment by mishoboss** [comment]
Yes. Tried it several times.

**Comment by Salamek** [comment]
Ah i see, i'm building QT6 version only for x86-64... Ill fix this by resolving #5

**Comment by mishoboss** [comment]
Hey @Salamek, any update on that one? It's a show-stopper :(

**Comment by Salamek** [comment]
Hmm current builds should be based on QT6 (1.2.2>) did you try?

**Comment by Salamek** [comment]
@mishoboss ping

**Comment by Salamek** [comment]
Hmm i assume this as resolved then... closing for now
