### ISSUE TITLE
Migrate to QT6 as default

### ISSUE THREAD

**Issue by Salamek** [Salamek/qiosk#5]
Migreate `qiosk` package to QT6 as default since QT6 is now part of Debian 12 (stable)
Also create fallback package qt5-qiosk to be used with QT5, this also means deprecation of qt6-qiosk package.

- [ ] Build qiosk package using QT6
- [ ] Create QT5 build `qt5-qiosk`
- [ ] Drop `qt6-qiosk`
- [ ] Change info in chromium-kiosk docs

To consider: Maybe make qiosk a metapackage and have qt6-qiosk as dep? with qt5-qiosk as optional dep?

**Comment by mishoboss** [comment]
Hey, @Salamek, any news on this one?

**Comment by Salamek** [comment]
@mishoboss should be resolved i 1.2.2
