### ISSUE TITLE
Navbar doesn't take any space on the website

### ISSUE THREAD

**Issue by drafolin** [Salamek/qiosk#6]
The navbar (back, forward, reload, home) doesn't offset the web page, therefore it oftens overlays some content of the page

**Comment by Salamek** [comment]
That is kinda expected behavior... but i understand in some cases it may not be desirable, i may add some config settings to make navbar not float over web page content.

**Comment by Salamek** [comment]
I have added new CLI config option --underlay-navbar to qiosk
