### ISSUE TITLE
F5 shortcut to refresh page

### ISSUE THREAD

**Issue by iHamsin** [Salamek/qiosk#9]
Hi
Thank you for your incredible project!
How can I turn on standard F5 or CTL+R shortcuts to refresh page?

**Comment by Salamek** [comment]
Well you can't...
Umm why would you want to do that? I kinda fail to see a use case for kiosk install...

**Comment by Salamek** [comment]
@iHamsin F5 works only when navbar is displayed and refresh button is enabled

**Comment by mjuweng** [comment]
Hi, hopefully this will be seen on a closed issue, it didn't make sense to create a duplicate. I have a +1 to this feature request!

I am building a kiosk intended to be used with a touchscreen for an internal network-served application. There are some edge cases where things change in the application and a page refresh is needed to see them. I don't want the refresh button there all the time, but want the refresh function available to the user in a pinch. Ideally i'd like to bind a touchscreen gesture. 

I can certainly write a script to configure and show the nav bar and then hide it again, and have the touch gesture run the script. But it would be WAY cleaner to simply have the gesture enter ctrl+r
